CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.kb_index_state (
  page_id text PRIMARY KEY,
  path text NOT NULL,
  title text NOT NULL,
  wiki_url text,
  last_seen_updated_at timestamptz,
  last_indexed_at timestamptz NOT NULL DEFAULT now(),
  content_hash text NOT NULL,
  chunk_count integer NOT NULL CHECK (chunk_count >= 0)
);

CREATE TABLE IF NOT EXISTS public.kb_chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id text NOT NULL REFERENCES public.kb_index_state(page_id) ON DELETE CASCADE,
  chunk_index integer NOT NULL CHECK (chunk_index >= 0),
  chunk_text text NOT NULL,
  path text NOT NULL,
  title text NOT NULL,
  wiki_url text,
  content_hash text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding vector(1536) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (page_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_kb_chunks_page_id ON public.kb_chunks(page_id);
CREATE INDEX IF NOT EXISTS idx_kb_chunks_path ON public.kb_chunks(path);
CREATE INDEX IF NOT EXISTS idx_kb_chunks_metadata ON public.kb_chunks USING gin(metadata);
CREATE INDEX IF NOT EXISTS idx_kb_chunks_embedding_cosine
  ON public.kb_chunks USING hnsw (embedding vector_cosine_ops);
