CREATE TABLE IF NOT EXISTS public.email_responder_state (
  mailbox text PRIMARY KEY,
  respond_after timestamptz NOT NULL DEFAULT now(),
  top_k integer NOT NULL DEFAULT 5 CHECK (top_k > 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.email_responder_state (mailbox, respond_after, top_k)
VALUES ('hello.wieland.collective@gmail.com', now(), 5)
ON CONFLICT (mailbox) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.email_responder_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mailbox text NOT NULL,
  message_key text NOT NULL,
  message_id text,
  imap_uid bigint,
  sender_email text NOT NULL,
  sender_raw text,
  subject text,
  received_at timestamptz,
  status text NOT NULL CHECK (
    status IN ('processing', 'replied', 'skipped_old', 'skipped_duplicate', 'failed')
  ),
  email_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  matched_pages jsonb,
  reply_subject text,
  reply_body text,
  send_result jsonb,
  claimed_at timestamptz,
  replied_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (mailbox, message_key)
);

CREATE INDEX IF NOT EXISTS idx_email_responder_messages_status
  ON public.email_responder_messages(status);

CREATE INDEX IF NOT EXISTS idx_email_responder_messages_received_at
  ON public.email_responder_messages(received_at);
