CREATE TABLE IF NOT EXISTS public.clients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address text NOT NULL,
  email text NOT NULL,
  phone_number text NOT NULL,
  bank_account_number text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.invoice (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL REFERENCES public.clients(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.item_type (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric(12, 2) NOT NULL CHECK (price >= 0),
  vat numeric(5, 2) NOT NULL CHECK (vat >= 0 AND vat <= 100)
);

CREATE TABLE IF NOT EXISTS public.items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES public.invoice(id) ON DELETE CASCADE,
  item_type_id integer NOT NULL REFERENCES public.item_type(id) ON DELETE RESTRICT,
  qty integer NOT NULL CHECK (qty > 0)
);

CREATE INDEX IF NOT EXISTS idx_invoice_client_id ON public.invoice(client_id);
CREATE INDEX IF NOT EXISTS idx_items_invoice_id ON public.items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_items_item_type_id ON public.items(item_type_id);
